### PR TITLE
pinterest template tag

### PR DESCRIPTION
**Pull request by brian101co**

### CODE REVIEW

**Review by fcurella — CHANGES_REQUESTED** [review]
Thank you! Can you add tests and update the README?

**Comment by brian101co** [comment]
Sure thing! I am new to testing, do you mind pointing me in the right direction on getting started with testing?

**Comment by brian101co** [comment]
@fcurella Alright, sounds good. I think I got it worked out and pushed my commit up to Github. Let me know what you think or if need to make adjustments. 

Thanks for your help!

**Comment by fcurella** [comment]
Looks good! Thank you!

**Comment by brian101co** [comment]
You're welcome! Thanks for the opportunity :)

**Pull request merged**
